version: "3"
services:
  app:
    image: node:latest
    environment:
      TZ: Asia/Tokyo
      NOTION_API_TOKEN: $NOTION_TOKEN
      NOTION_DB_ID: $DATABASE_ID
    volumes:
      - .:/app
    working_dir: /app
